let num = [5, 8, 2, 9, 3]
num.push(1)
num.sort()
console.log(num)
console.log(` Nosso vetor é de ${num.length} posições `)
console.log(`O primeiro valor do vetor é ${num[0]}`)
let pos = num.indexOf(5)
let pos2 = num.indexOf(8)
let pos3 = num.indexOf(3)
console.log(`o valor 5 está na posição ${pos}`)
if (pos == -1)
    console.log('o valor não foi encontrado')
console.log (`o valor 8 está na posição ${pos2}`)
if (pos2 == -1)
    console.log('o valor não foi encontrado')
console.log(`O valor 3 está na posição ${pos3}`)
if (pos3 == -1)
    console.log('o valor não foi encontrado')